[main]
mkdocs_dir = "docs"
docs_dir_name = "docs"
input_path = "src"
create_mkdocs = false

[project]
name = "Ekono"
description = "Ekono is a system for building customisable AI pipelines by chaining a ton of models. There can be an infinite number of combinations. There's about 50 such types of models available. Each type having between 2 and 10 state of the art models."
repo_url = "https://github.com/re-masashi/ekono"

[ignore]
patterns = [
    ".venv",
    "venv",
    "node_modules",
    ".git",
    "__pycache__",
    ".env",
    "requirements.txt",
    "*.css",
    "*.svg"
]

[llm]
provider = "gemini"  # Options: gemini, openai, ollama, etc.
api_key_file = "secrets/gemini_api_key.txt"  # Path to the file containing the API key
# base_url = "http://localhost:11434"  # Required for Ollama
model = "gemini-2.0-flash-exp"  # Model name